#pragma once

// ============================================================================
// core/parts/dict_io.hpp
//
// Save / load PartDictionary using the trained-only format.
//
// Files store ONLY trained parts (multi-char Whole, Start, Mid, End,
// observed Delimiter). Singletons (Letter atoms) and special
// characters (single-char Whole atoms, connector Delimiter atoms) are
// deterministically regenerated by augment_with_atoms() at load time.
//
// ----- TEXT FORMAT --------------------------------------------------
//
// One value per line. Kind is encoded by the "##" position marker.
// Delimiters are placed in a final [delim] section because they
// don't fit the "##" convention.
//
//   the                    ← Whole "the"     (no ## anywhere)
//   am
//   cata##                 ← Start "cata"    (## at end only)
//   un##
//   ##stro##               ← Mid "stro"      (## at both ends)
//   ##port##
//   ##phe                  ← End "phe"       (## at start only)
//   ##ing
//   [delim]
//   \x20                   ← Delimiter " "   (escape encoded)
//   .
//   \x0A
//
// Parse rules above [delim]:
//   no ##                  → Whole
//   ends with ## only      → Start
//   begins with ## only    → End
//   ## at both ends        → Mid
//
// Delimiter escape codes: \n \t \r \\ \xHH for arbitrary bytes.
//
// ----- BINARY FORMAT ------------------------------------------------
//
// Compact per-part encoding: one uint8 kind flag followed by a
// uint16 length and the value bytes.
//
//   Header (8 bytes):
//     "BDI2"            (4 bytes magic, distinguishes from old format)
//     uint8 version     (= 1)
//     uint8 reserved    (= 0)
//     uint16 reserved   (= 0)
//
//   Then a sequence of part records:
//     uint8  kind        (0=Start, 1=End, 2=Mid, 4=Whole, 5=Delimiter)
//     uint16 length      (little-endian, value bytes)
//     bytes  value
//
//   EOF terminates the record list. Letter (kind=3) is NEVER written.
//
// All multi-byte ints are little-endian.
// ============================================================================

#include "dictionary.hpp"

#include <iosfwd>

namespace core::parts {

// ----- Text -------------------------------------------------------
void save_dict_text(const PartDictionary& dict, std::ostream& out);
PartDictionary load_dict_text(std::istream& in);

// ----- Binary -----------------------------------------------------
void save_dict_binary(const PartDictionary& dict, std::ostream& out);
PartDictionary load_dict_binary(std::istream& in);

}  // namespace core::parts
