// ============================================================================
// core/parts/src/dict_io.cpp
// ============================================================================

#include "dict_io.hpp"

#include "dict_augment.hpp"

#include <array>
#include <cstdint>
#include <cstring>
#include <iomanip>
#include <istream>
#include <ostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>

namespace core::parts {

namespace {

// ---- Augment-set membership predicate ----------------------------

const char* const kConnectors[] = {"-", "'", "&", ",", ".", "$"};

bool is_connector(std::string_view v) {
  if (v.size() != 1) return false;
  for (const char* c : kConnectors) {
    if (v[0] == c[0]) return true;
  }
  return false;
}

// True if the part would be regenerated by augment_with_atoms().
// Save filters these out; load skips writing them (none in file).
bool is_augmented(const PartKey& k) {
  if (k.kind == Kind::Letter) return true;
  if (k.kind == Kind::Whole && k.value.size() == 1) {
    const char c = k.value[0];
    if (c >= 'a' && c <= 'z') return true;
    if (c >= '0' && c <= '9') return true;
    if (is_connector(k.value)) return true;
  }
  if (k.kind == Kind::Delimiter && is_connector(k.value)) {
    return true;
  }
  return false;
}

// ---- Text escape / unescape (for delimiters) ---------------------

std::string escape_value(std::string_view s) {
  std::string out;
  out.reserve(s.size());
  for (unsigned char c : s) {
    switch (c) {
      case '\n': out += "\\n";  break;
      case '\t': out += "\\t";  break;
      case '\r': out += "\\r";  break;
      case '\\': out += "\\\\"; break;
      default:
        if (c < 0x20 || c == 0x7f) {
          char buf[5];
          std::snprintf(buf, sizeof(buf), "\\x%02X", c);
          out += buf;
        } else {
          out += static_cast<char>(c);
        }
    }
  }
  return out;
}

int hex_digit(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  return -1;
}

std::string unescape_value(std::string_view s) {
  std::string out;
  out.reserve(s.size());
  for (std::size_t i = 0; i < s.size(); ) {
    if (s[i] != '\\') {
      out += s[i++];
      continue;
    }
    if (i + 1 >= s.size()) {
      out += '\\';
      ++i;
      continue;
    }
    const char esc = s[i + 1];
    switch (esc) {
      case 'n':  out += '\n'; i += 2; break;
      case 't':  out += '\t'; i += 2; break;
      case 'r':  out += '\r'; i += 2; break;
      case '\\': out += '\\'; i += 2; break;
      case 'x': {
        if (i + 3 < s.size()) {
          const int h = hex_digit(s[i + 2]);
          const int l = hex_digit(s[i + 3]);
          if (h >= 0 && l >= 0) {
            out += static_cast<char>((h << 4) | l);
            i += 4;
            break;
          }
        }
        out += '\\';
        ++i;
        break;
      }
      default:
        out += '\\';
        ++i;
        break;
    }
  }
  return out;
}

// ---- ## convention helpers ---------------------------------------

bool starts_with_hashhash(std::string_view s) {
  return s.size() >= 2 && s[0] == '#' && s[1] == '#';
}
bool ends_with_hashhash(std::string_view s) {
  const std::size_t n = s.size();
  return n >= 2 && s[n - 2] == '#' && s[n - 1] == '#';
}

}  // namespace

// =============================================================================
// TEXT
// =============================================================================

void save_dict_text(const PartDictionary& dict, std::ostream& out) {
  // Pass 1: Whole / Start / Mid / End in dict ID order (so reload
  // reproduces the same insertion order).
  for (const PartKey& k : dict.all_parts()) {
    if (is_augmented(k)) continue;
    switch (k.kind) {
      case Kind::Whole:
        out << k.value << '\n';
        break;
      case Kind::Start:
        out << k.value << "##\n";
        break;
      case Kind::Mid:
        out << "##" << k.value << "##\n";
        break;
      case Kind::End:
        out << "##" << k.value << '\n';
        break;
      case Kind::Letter:
      case Kind::Delimiter:
        // handled below or filtered above
        break;
    }
  }

  // Pass 2: Delimiter section.
  out << "[delim]\n";
  for (const PartKey& k : dict.all_parts()) {
    if (k.kind != Kind::Delimiter) continue;
    if (is_augmented(k)) continue;
    out << escape_value(k.value) << '\n';
  }
}

PartDictionary load_dict_text(std::istream& in) {
  PartDictionary dict;
  std::string line;
  bool in_delim = false;

  while (std::getline(in, line)) {
    // Strip trailing CR (Windows line endings).
    while (!line.empty() && (line.back() == '\r')) line.pop_back();
    if (line.empty()) continue;

    if (line == "[delim]") {
      in_delim = true;
      continue;
    }

    if (in_delim) {
      dict.add(Kind::Delimiter, unescape_value(line));
      continue;
    }

    const bool s = starts_with_hashhash(line);
    const bool e = ends_with_hashhash(line);
    if (s && e) {
      if (line.size() >= 4) {
        dict.add(Kind::Mid, line.substr(2, line.size() - 4));
      }
    } else if (e) {
      dict.add(Kind::Start, line.substr(0, line.size() - 2));
    } else if (s) {
      dict.add(Kind::End, line.substr(2));
    } else {
      dict.add(Kind::Whole, line);
    }
  }

  augment_with_atoms(dict);
  return dict;
}

// =============================================================================
// BINARY
// =============================================================================

namespace {

constexpr std::array<char, 4> kMagicBDI2 = {'B', 'D', 'I', '2'};
constexpr std::uint8_t kBinaryVersion = 1;

void write_u8 (std::ostream& out, std::uint8_t  v) {
  out.put(static_cast<char>(v));
}
void write_u16(std::ostream& out, std::uint16_t v) {
  const char b[2] = {
    static_cast<char>(v & 0xff),
    static_cast<char>((v >> 8) & 0xff),
  };
  out.write(b, 2);
}
void write_bytes(std::ostream& out, const std::string& s) {
  if (!s.empty()) out.write(s.data(), static_cast<std::streamsize>(s.size()));
}

bool read_u8(std::istream& in, std::uint8_t& v) {
  char c;
  if (!in.get(c)) return false;
  v = static_cast<std::uint8_t>(static_cast<unsigned char>(c));
  return true;
}
bool read_u16(std::istream& in, std::uint16_t& v) {
  unsigned char b[2];
  in.read(reinterpret_cast<char*>(b), 2);
  if (in.gcount() != 2) return false;
  v = static_cast<std::uint16_t>(b[0]) |
      (static_cast<std::uint16_t>(b[1]) << 8);
  return true;
}

std::uint8_t kind_to_byte(Kind k) {
  switch (k) {
    case Kind::Start:     return 0;
    case Kind::End:       return 1;
    case Kind::Mid:       return 2;
    case Kind::Letter:    return 3;
    case Kind::Whole:     return 4;
    case Kind::Delimiter: return 5;
  }
  return 255;
}

bool byte_to_kind(std::uint8_t b, Kind& out) {
  switch (b) {
    case 0: out = Kind::Start;     return true;
    case 1: out = Kind::End;       return true;
    case 2: out = Kind::Mid;       return true;
    case 3: out = Kind::Letter;    return true;
    case 4: out = Kind::Whole;     return true;
    case 5: out = Kind::Delimiter; return true;
    default: return false;
  }
}

}  // namespace

void save_dict_binary(const PartDictionary& dict, std::ostream& out) {
  // Header.
  out.write(kMagicBDI2.data(), 4);
  write_u8(out, kBinaryVersion);
  write_u8(out, 0);            // reserved
  write_u16(out, 0);           // reserved

  // Records.
  for (const PartKey& k : dict.all_parts()) {
    if (is_augmented(k)) continue;
    if (k.value.size() > 0xffff) {
      throw std::runtime_error("part value exceeds uint16 length");
    }
    write_u8(out, kind_to_byte(k.kind));
    write_u16(out, static_cast<std::uint16_t>(k.value.size()));
    write_bytes(out, k.value);
  }
}

PartDictionary load_dict_binary(std::istream& in) {
  // Header.
  char magic[4];
  in.read(magic, 4);
  if (in.gcount() != 4 ||
      std::memcmp(magic, kMagicBDI2.data(), 4) != 0) {
    throw std::runtime_error("load_dict_binary: bad magic (expected BDI2)");
  }
  std::uint8_t version = 0, reserved8 = 0;
  std::uint16_t reserved16 = 0;
  if (!read_u8(in, version) ||
      !read_u8(in, reserved8) ||
      !read_u16(in, reserved16)) {
    throw std::runtime_error("load_dict_binary: truncated header");
  }
  if (version != kBinaryVersion) {
    std::ostringstream msg;
    msg << "load_dict_binary: unsupported version " << static_cast<int>(version);
    throw std::runtime_error(msg.str());
  }

  PartDictionary dict;

  while (true) {
    std::uint8_t kind_byte = 0;
    if (!read_u8(in, kind_byte)) break;  // clean EOF
    Kind kind;
    if (!byte_to_kind(kind_byte, kind)) {
      throw std::runtime_error("load_dict_binary: bad kind byte");
    }
    std::uint16_t len = 0;
    if (!read_u16(in, len)) {
      throw std::runtime_error("load_dict_binary: truncated length");
    }
    std::string value(len, '\0');
    if (len > 0) {
      in.read(value.data(), len);
      if (in.gcount() != static_cast<std::streamsize>(len)) {
        throw std::runtime_error("load_dict_binary: truncated value");
      }
    }
    dict.add(kind, std::move(value));
  }

  augment_with_atoms(dict);
  return dict;
}

}  // namespace core::parts
